<?php

namespace App\Services;

use App\Models\Story;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class GeminiService
{
    private string $apiKey;
    private string $baseUrl;
    private string $model;

    public function __construct()
    {
        $this->apiKey = config('gemini.api_key', '');
        $this->baseUrl = config('gemini.base_url');
        $this->model = config('gemini.model');
    }

    /**
     * Generate a story using Gemini Flash AI
     */
    public function generateStory(Story $story): array
    {
        if (empty($this->apiKey)) {
            throw new \Exception('Gemini API key not configured. Add GEMINI_API_KEY to your .env file.');
        }

        $prompt = $this->buildPrompt($story);

        try {
            $response = Http::withHeaders([
                'Content-Type' => 'application/json',
            ])->timeout(config('gemini.timeout', 30))
            ->post("{$this->baseUrl}/models/{$this->model}:generateContent?key={$this->apiKey}", [
                'contents' => [
                    [
                        'parts' => [
                            ['text' => $prompt]
                        ]
                    ]
                ],
                'generationConfig' => [
                    'temperature' => config('gemini.temperature', 0.7),
                    'maxOutputTokens' => config('gemini.max_tokens', 2048),
                ]
            ]);

            if ($response->successful()) {
                $data = $response->json();
                $generatedText = $data['candidates'][0]['content']['parts'][0]['text'] ?? '';
                
                if (empty($generatedText)) {
                    throw new \Exception('No content generated by AI');
                }

                return [
                    'success' => true,
                    'content' => $generatedText,
                    'usage' => $data['usageMetadata'] ?? null
                ];
            } else {
                Log::error('Gemini API error', [
                    'status' => $response->status(),
                    'response' => $response->body()
                ]);
                
                throw new \Exception('Gemini API error: ' . $response->body());
            }

        } catch (\Exception $e) {
            Log::error('Gemini generation failed', [
                'story_id' => $story->id,
                'error' => $e->getMessage()
            ]);

            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Build the prompt for Gemini Flash based on story data
     */
    private function buildPrompt(Story $story): string
    {
        $chapters = $story->chapters()->orderBy('order')->get();
        $settings = $story->ai_settings ?? [];

        $tone = $settings['tone'] ?? 'vriendelijk';
        $style = $settings['style'] ?? 'verhaal';
        $length = $settings['length'] ?? 'medium';

        $prompt = "Schrijf een {$tone} verhaal in {$style} stijl.\n\n";
        
        if (!empty($story->description)) {
            $prompt .= "Beschrijving: {$story->description}\n\n";
        }

        $prompt .= "Titel: {$story->title}\n\n";

        if ($length === 'kort') {
            $prompt .= "Schrijf een kort verhaal van 2-3 alinea's.\n\n";
        } elseif ($length === 'lang') {
            $prompt .= "Schrijf een uitgebreid verhaal van 10+ alinea's.\n\n";
        } else {
            $prompt .= "Schrijf een verhaal van gemiddelde lengte (5-7 alinea's).\n\n";
        }

        $prompt .= "Gebaseerd op deze hoofdstukken:\n\n";

        foreach ($chapters as $index => $chapter) {
            $chapterNum = $index + 1;
            $prompt .= "Hoofdstuk {$chapterNum}: {$chapter->title}\n";
            if (!empty($chapter->content)) {
                $prompt .= "Notities: {$chapter->content}\n";
            }
            $prompt .= "\n";
        }

        $prompt .= "\nSchrijf het verhaal in het Nederlands en maak er een samenhangend, leesbaar verhaal van. ";
        $prompt .= "Gebruik de hoofdstukken als leidraad maar schrijf het uit als een volledig verhaal. ";
        $prompt .= "Voeg geen extra hoofdstuk titels toe in het verhaal zelf.";

        return $prompt;
    }

    /**
     * Test the Gemini API connection
     */
    public function testConnection(): bool
    {
        try {
            $response = Http::timeout(5)
                ->get("{$this->baseUrl}/models/{$this->model}?key={$this->apiKey}");
            
            return $response->successful();
        } catch (\Exception $e) {
            return false;
        }
    }
}
